package fluxkontext

// Code generated by SdkContractGenerator. DO NOT EDIT.

var contractSchema = map[string]any{"text-to-image": map[string]any{"models": []any{"flux-kontext-max", "flux-kontext-pro"}, "fields_by_model": map[string]any{"flux-kontext-max": map[string]any{"aspect_ratio": map[string]any{"enum": []any{"21:9", "16:9", "4:3", "1:1", "3:4", "9:16"}}, "model": map[string]any{"required": true}, "output_format": map[string]any{"enum": []any{"jpeg", "png"}}, "prompt": map[string]any{"required": true}, "safety_tolerance": map[string]any{"type": "integer"}}, "flux-kontext-pro": map[string]any{"aspect_ratio": map[string]any{"enum": []any{"21:9", "16:9", "4:3", "1:1", "3:4", "9:16"}}, "model": map[string]any{"required": true}, "output_format": map[string]any{"enum": []any{"jpeg", "png"}}, "prompt": map[string]any{"required": true}, "safety_tolerance": map[string]any{"type": "integer"}}}}}
