# frozen_string_literal: true

# Code generated by SdkContractGenerator. DO NOT EDIT.

module RunApi
  module FluxKontext
    CONTRACT = {
      "text-to-image" => {
        "models" => ["flux-kontext-max", "flux-kontext-pro"],
        "fields_by_model" => {
          "flux-kontext-max" => {
            "aspect_ratio" => {
              "enum" => ["21:9", "16:9", "4:3", "1:1", "3:4", "9:16"]
            },
            "model" => {
              "required" => true
            },
            "output_format" => {
              "enum" => ["jpeg", "png"]
            },
            "prompt" => {
              "required" => true
            },
            "safety_tolerance" => {
              "type" => "integer"
            }
          },
          "flux-kontext-pro" => {
            "aspect_ratio" => {
              "enum" => ["21:9", "16:9", "4:3", "1:1", "3:4", "9:16"]
            },
            "model" => {
              "required" => true
            },
            "output_format" => {
              "enum" => ["jpeg", "png"]
            },
            "prompt" => {
              "required" => true
            },
            "safety_tolerance" => {
              "type" => "integer"
            }
          }
        }
      }
    }.freeze
  end
end
