# Code generated by SdkContractGenerator. DO NOT EDIT.

CONTRACT = {
    "text-to-image": {
        "models": ["flux-kontext-max", "flux-kontext-pro"],
        "fields_by_model": {
            "flux-kontext-max": {
                "aspect_ratio": {
                    "enum": ["21:9", "16:9", "4:3", "1:1", "3:4", "9:16"]
                },
                "model": {
                    "required": True
                },
                "output_format": {
                    "enum": ["jpeg", "png"]
                },
                "prompt": {
                    "required": True
                },
                "safety_tolerance": {
                    "type": "integer"
                }
            },
            "flux-kontext-pro": {
                "aspect_ratio": {
                    "enum": ["21:9", "16:9", "4:3", "1:1", "3:4", "9:16"]
                },
                "model": {
                    "required": True
                },
                "output_format": {
                    "enum": ["jpeg", "png"]
                },
                "prompt": {
                    "required": True
                },
                "safety_tolerance": {
                    "type": "integer"
                }
            }
        }
    }
}
